package techguns.client.models.guns;

import net.minecraft.client.render.model.json.ModelTransformationMode;
import techguns.client.models.ModelPart;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.entity.Entity;
import techguns.client.models.ModelMultipart;

public class ModelVector extends ModelMultipart {

    public ModelPart Grip1;
    public ModelPart Trigger02;
    public ModelPart Grip02;
    public ModelPart Eotech01;
    public ModelPart Receiver03;
    public ModelPart TopRails;
    public ModelPart Eotech02;
    public ModelPart Eotech03;
    public ModelPart Eotech04;
    public ModelPart Grip01;
    public ModelPart RedDot;
    public ModelPart Receiver02;
    public ModelPart Receiver03_1;
    public ModelPart Receiver04;
    public ModelPart FrontRails01;
    public ModelPart Grip03;
    public ModelPart Bottom;
    public ModelPart Receiver05;
    public ModelPart Bottom2;
    public ModelPart Barrel;
    public ModelPart Barrel02;
    public ModelPart Magazine;
    public ModelPart stock;
    public ModelPart stock02;
    public ModelPart stock03;
    public ModelPart stock04;
    public ModelPart stock05;
    public ModelPart stock06;

    public ModelVector() {
        super(RenderLayer::getEntitySolid);
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.stock03 = new ModelPart(this, 82, 16);
        this.stock03.setPivot(-2.0F, -0.2F, 25.0F);
        this.stock03.addCuboid(0.0F, 0.0F, 0.0F, 3, 10, 2, 0.0F);
        this.Receiver04 = new ModelPart(this, 34, 0);
        this.Receiver04.setPivot(-2.0F, 0.0F, -14.0F);
        this.Receiver04.addCuboid(0.0F, 0.0F, 0.0F, 3, 3, 10, 0.0F);
        this.Eotech03 = new ModelPart(this, 0, 10);
        this.Eotech03.setPivot(-0.5F, -7.7F, 0.4F);
        this.Eotech03.addCuboid(-2.0F, -0.5F, -2.0F, 4, 1, 4, 0.0F);
        this.stock = new ModelPart(this, 72, 0);
        this.stock.setPivot(0.0F, -2.0F, 11.0F);
        this.stock.addCuboid(-2.0F, 0.0F, 0.0F, 3, 2, 11, 0.0F);
        this.Receiver03 = new ModelPart(this, 0, 0);
        this.Receiver03.setPivot(-0.5F, -3.0F, -14.0F);
        this.Receiver03.addCuboid(-2.0F, 0.0F, 0.0F, 4, 3, 25, 0.0F);
        this.Eotech02 = new ModelPart(this, 65, 32);
        this.Eotech02.setPivot(-0.5F, -4.5F, -1.0F);
        this.Eotech02.addCuboid(-2.0F, -1.5F, -4.5F, 4, 3, 9, 0.0F);
        this.stock04 = new ModelPart(this, 72, 20);
        this.stock04.setPivot(-0.5F, 7.3F, 23.0F);
        this.stock04.addCuboid(-1.0F, -1.0F, 0.0F, 2, 2, 2, 0.0F);
        this.setRotation(stock04, 0.0F, 0.0F, 0.7853981633974483F);
        this.Barrel02 = new ModelPart(this, 10, 0);
        this.Barrel02.setPivot(-0.5F, 1.2F, -17.0F);
        this.Barrel02.addCuboid(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
        this.setRotation(Barrel02, 0.0F, -0.0F, 0.7853981633974483F);
        this.FrontRails01 = new ModelPart(this, 37, 16);
        this.FrontRails01.setPivot(-1.5F, 3.0F, -13.5F);
        this.FrontRails01.addCuboid(0.0F, 0.0F, 0.0F, 2, 1, 7, 0.0F);
        this.Grip1 = new ModelPart(this, 0, 29);
        this.Grip1.setPivot(-2.0F, -0.1F, 5.9F);
        this.Grip1.addCuboid(0.0F, 0.0F, 0.0F, 3, 10, 4, 0.0F);
        this.setRotation(Grip1, 0.3490658503988659F, -0.0F, 0.0F);
        this.Bottom = new ModelPart(this, 94, 12);
        this.Bottom.setPivot(-1.0F, 9.4F, -4.2F);
        this.Bottom.addCuboid(-1.0F, 0.0F, 0.0F, 3, 1, 10, 0.0F);
        this.Magazine = new ModelPart(this, 60, 0);
        this.Magazine.setPivot(-0.5F, 9.0F, -4.3F);
        this.Magazine.addCuboid(-1.0F, 0.0F, 0.0F, 2, 11, 3, 0.0F);
        this.setRotation(Magazine, 0.3490658503988659F, -0.0F, 0.0F);
        this.Receiver05 = new ModelPart(this, 11, 16);
        this.Receiver05.setPivot(-0.5F, 9.6F, 5.9F);
        this.Receiver05.addCuboid(-1.5F, -1.0F, -1.0F, 3, 1, 2, 0.0F);
        this.setRotation(Receiver05, -0.3490658503988659F, 0.0F, 0.0F);
        this.Barrel = new ModelPart(this, 17, 0);
        this.Barrel.setPivot(-0.5F, 1.2F, -16.0F);
        this.Barrel.addCuboid(-0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F);
        this.setRotation(Barrel, 0.0F, 0.0F, 0.7853981633974483F);
        this.Grip02 = new ModelPart(this, 35, 13);
        this.Grip02.setPivot(-2.0F, 4.0F, -10.5F);
        this.Grip02.addCuboid(0.0F, 0.0F, 0.0F, 2, 7, 2, 0.0F);
        this.setRotation(Grip02, 0.0F, 0.7853981633974483F, 0.0F);
        this.TopRails = new ModelPart(this, 36, 23);
        this.TopRails.setPivot(-1.5F, -4.0F, -13.0F);
        this.TopRails.addCuboid(0.0F, 0.0F, 0.0F, 2, 1, 23, 0.0F);
        this.Bottom2 = new ModelPart(this, 91, 0);
        this.Bottom2.setPivot(-1.0F, 8.4F, -3.5F);
        this.Bottom2.addCuboid(-1.0F, 0.0F, 0.0F, 3, 1, 9, 0.0F);
        this.RedDot = new ModelPart(this, 0, 11);
        this.RedDot.setPivot(-1.0F+0.45F, -7.1F+0.45F, 1.0F+0.45f);
        this.RedDot.addCuboid(0.0F, 0.0F, 0.0F, 0.1f, 0.1f, 0, 0.0F);
        this.Grip01 = new ModelPart(this, 49, 14);
        this.Grip01.setPivot(-2.0F, 3.1F, -12.5F);
        this.Grip01.addCuboid(0.0F, 0.0F, 0.0F, 3, 1, 4, 0.0F);
        this.Eotech01 = new ModelPart(this, 0, 3);
        this.Eotech01.setPivot(0.7F, -6.5F, 2.0F);
        this.Eotech01.addCuboid(-0.5F, -1.0F, -4.0F, 1, 2, 4, 0.0F);
        this.stock02 = new ModelPart(this, 64, 15);
        this.stock02.setPivot(-1.0F, -1.1F, 20.1F);
        this.stock02.addCuboid(0.0F, 0.0F, 0.0F, 1, 10, 2, 0.0F);
        this.setRotation(stock02, 0.3490658503988659F, -0.0F, 0.0F);
        this.stock05 = new ModelPart(this, 72, 25);
        this.stock05.setPivot(-0.5F, 1.8F, 21.0F);
        this.stock05.addCuboid(-1.0F, -1.0F, 0.0F, 2, 2, 4, 0.0F);
        this.setRotation(stock05, 0.0F, -0.0F, 0.7853981633974483F);
        this.Receiver02 = new ModelPart(this, 16, 29);
        this.Receiver02.setPivot(-1.0F, 0.0F, -3.0F);
        this.Receiver02.addCuboid(-1.0F, 0.0F, 0.0F, 3, 11, 5, 0.0F);
        this.setRotation(Receiver02, 0.3490658503988659F, -0.0F, 0.0F);
        this.stock06 = new ModelPart(this, 83, 30);
        this.stock06.setPivot(-0.5F, -3.0F, 11.0F);
        this.stock06.addCuboid(-1.5F, 0.0F, 0.0F, 3, 1, 3, 0.0F);
        this.setRotation(stock06, -0.3490658503988659F, 0.0F, 0.0F);
        this.Eotech04 = new ModelPart(this, 0, 3);
        this.Eotech04.setPivot(-1.7F, -6.5F, 0.4F);
        this.Eotech04.addCuboid(-0.5F, -1.0F, -2.0F, 1, 2, 4, 0.0F);
        this.Receiver03_1 = new ModelPart(this, 34, 29);
        this.Receiver03_1.setPivot(-1.0F, 0.0F, -8.0F);
        this.Receiver03_1.addCuboid(-1.0F, 0.0F, 0.0F, 3, 11, 5, 0.0F);
        this.setRotation(Receiver03_1, 0.3490658503988659F, -0.0F, 0.0F);
        this.Grip03 = new ModelPart(this, 0, 19);
        this.Grip03.setPivot(-0.5F, 9.5F, 5.3F);
        this.Grip03.addCuboid(-1.5F, 0.0F, 0.0F, 3, 1, 4, 0.0F);
        this.setRotation(Grip03, 0.31066860685499065F, -0.0F, 0.0F);
        this.Trigger02 = new ModelPart(this, 20, 20);
        this.Trigger02.setPivot(-1.0F, -0.5F, 5.0F);
        this.Trigger02.addCuboid(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
        this.setRotation(Trigger02, -0.17453292519943295F, -0.0F, 0.0F);
    }

	@Override
	public void render(Entity entityIn, MatrixStack matrices, VertexConsumer vertices, int ammoLeft,
                       float reloadProgress, ModelTransformationMode transformType, int part, float fireProgress, float chargeProgress, int light,
                       int overlay) {

        this.stock03.render(matrices, vertices, light, overlay);
        this.Receiver04.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Eotech03.pivotX * scale, this.Eotech03.pivotY * scale, this.Eotech03.pivotZ * scale);
        matrices.translate(this.Eotech03.pitch * scale, this.Eotech03.yaw * scale, this.Eotech03.roll * scale);
        matrices.scale(0.8f, 0.8f, 0.8f);
        matrices.translate(-this.Eotech03.pivotX * scale, -this.Eotech03.pivotY * scale, -this.Eotech03.pivotZ * scale);
        matrices.translate(-this.Eotech03.pitch * scale, -this.Eotech03.yaw * scale, -this.Eotech03.roll * scale);
        this.Eotech03.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.stock.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Receiver03.pivotX * scale, this.Receiver03.pivotY * scale, this.Receiver03.pivotZ * scale);
        matrices.translate(this.Receiver03.pitch * scale, this.Receiver03.yaw * scale, this.Receiver03.roll * scale);
        matrices.scale(0.8f, 1.0f, 1.0f);
        matrices.translate(-this.Receiver03.pivotX * scale, -this.Receiver03.pivotY * scale, -this.Receiver03.pivotZ * scale);
        matrices.translate(-this.Receiver03.pitch * scale, -this.Receiver03.yaw * scale, -this.Receiver03.roll * scale);
        this.Receiver03.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.Eotech02.pivotX * scale, this.Eotech02.pivotY * scale, this.Eotech02.pivotZ * scale);
        matrices.translate(this.Eotech02.pitch * scale, this.Eotech02.yaw * scale, this.Eotech02.roll * scale);
        matrices.scale(0.8f, 0.8f, 0.8f);
        matrices.translate(-this.Eotech02.pivotX * scale, -this.Eotech02.pivotY * scale, -this.Eotech02.pivotZ * scale);
        matrices.translate(-this.Eotech02.pitch * scale, -this.Eotech02.yaw * scale, -this.Eotech02.roll * scale);
        this.Eotech02.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.stock04.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Barrel02.pivotX * scale, this.Barrel02.pivotY * scale, this.Barrel02.pivotZ * scale);
        matrices.translate(this.Barrel02.pitch * scale, this.Barrel02.yaw * scale, this.Barrel02.roll * scale);
        matrices.scale(0.7f, 0.7f, 1.0f);
        matrices.translate(-this.Barrel02.pivotX * scale, -this.Barrel02.pivotY * scale, -this.Barrel02.pivotZ * scale);
        matrices.translate(-this.Barrel02.pitch * scale, -this.Barrel02.yaw * scale, -this.Barrel02.roll * scale);
        this.Barrel02.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.FrontRails01.render(matrices, vertices, light, overlay);
        this.Grip1.render(matrices, vertices, light, overlay);
        this.Bottom.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Magazine.pivotX * scale, this.Magazine.pivotY * scale, this.Magazine.pivotZ * scale);
        matrices.translate(this.Magazine.pitch * scale, this.Magazine.yaw * scale, this.Magazine.roll * scale);
        matrices.scale(0.99f, 1.0f, 1.0f);
        matrices.translate(-this.Magazine.pivotX * scale, -this.Magazine.pivotY * scale, -this.Magazine.pivotZ * scale);
        matrices.translate(-this.Magazine.pitch * scale, -this.Magazine.yaw * scale, -this.Magazine.roll * scale);
        this.Magazine.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.Receiver05.pivotX * scale, this.Receiver05.pivotY * scale, this.Receiver05.pivotZ * scale);
        matrices.translate(this.Receiver05.pitch * scale, this.Receiver05.yaw * scale, this.Receiver05.roll * scale);
        matrices.scale(0.98f, 1.0f, 1.0f);
        matrices.translate(-this.Receiver05.pivotX * scale, -this.Receiver05.pivotY * scale, -this.Receiver05.pivotZ * scale);
        matrices.translate(-this.Receiver05.pitch * scale, -this.Receiver05.yaw * scale, -this.Receiver05.roll * scale);
        this.Receiver05.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.Barrel.render(matrices, vertices, light, overlay);
        this.Grip02.render(matrices, vertices, light, overlay);
        this.TopRails.render(matrices, vertices, light, overlay);
        this.Bottom2.render(matrices, vertices, light, overlay);
        this.RedDot.render(matrices, vertices, bright_light, overlay);
        this.Grip01.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Eotech01.pivotX * scale, this.Eotech01.pivotY * scale, this.Eotech01.pivotZ * scale);
        matrices.translate(this.Eotech01.pitch * scale, this.Eotech01.yaw * scale, this.Eotech01.roll * scale);
        matrices.scale(0.8f, 0.8f, 0.8f);
        matrices.translate(-this.Eotech01.pivotX * scale, -this.Eotech01.pivotY * scale, -this.Eotech01.pivotZ * scale);
        matrices.translate(-this.Eotech01.pitch * scale, -this.Eotech01.yaw * scale, -this.Eotech01.roll * scale);
        this.Eotech01.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.stock02.render(matrices, vertices, light, overlay);
        this.stock05.render(matrices, vertices, light, overlay);
        matrices.push();
        matrices.translate(this.Receiver02.pivotX * scale, this.Receiver02.pivotY * scale, this.Receiver02.pivotZ * scale);
        matrices.translate(this.Receiver02.pitch * scale, this.Receiver02.yaw * scale, this.Receiver02.roll * scale);
        matrices.scale(0.99f, 1.0f, 1.0f);
        matrices.translate(-this.Receiver02.pivotX * scale, -this.Receiver02.pivotY * scale, -this.Receiver02.pivotZ * scale);
        matrices.translate(-this.Receiver02.pitch * scale, -this.Receiver02.yaw * scale, -this.Receiver02.roll * scale);
        this.Receiver02.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.stock06.pivotX * scale, this.stock06.pivotY * scale, this.stock06.pivotZ * scale);
        matrices.translate(this.stock06.pitch * scale, this.stock06.yaw * scale, this.stock06.roll * scale);
        matrices.scale(0.99f, 1.0f, 1.0f);
        matrices.translate(-this.stock06.pivotX * scale, -this.stock06.pivotY * scale, -this.stock06.pivotZ * scale);
        matrices.translate(-this.stock06.pitch * scale, -this.stock06.yaw * scale, -this.stock06.roll * scale);
        this.stock06.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.Eotech04.pivotX * scale, this.Eotech04.pivotY * scale, this.Eotech04.pivotZ * scale);
        matrices.translate(this.Eotech04.pitch * scale, this.Eotech04.yaw * scale, this.Eotech04.roll * scale);
        matrices.scale(0.8f, 0.8f, 0.8f);
        matrices.translate(-this.Eotech04.pivotX * scale, -this.Eotech04.pivotY * scale, -this.Eotech04.pivotZ * scale);
        matrices.translate(-this.Eotech04.pitch * scale, -this.Eotech04.yaw * scale, -this.Eotech04.roll * scale);
        this.Eotech04.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.Receiver03_1.pivotX * scale, this.Receiver03_1.pivotY * scale, this.Receiver03_1.pivotZ * scale);
        matrices.translate(this.Receiver03_1.pitch * scale, this.Receiver03_1.yaw * scale, this.Receiver03_1.roll * scale);
        matrices.scale(0.99f, 1.0f, 1.0f);
        matrices.translate(-this.Receiver03_1.pivotX * scale, -this.Receiver03_1.pivotY * scale, -this.Receiver03_1.pivotZ * scale);
        matrices.translate(-this.Receiver03_1.pitch * scale, -this.Receiver03_1.yaw * scale, -this.Receiver03_1.roll * scale);
        this.Receiver03_1.render(matrices, vertices, light, overlay);
        matrices.pop();
        matrices.push();
        matrices.translate(this.Grip03.pivotX * scale, this.Grip03.pivotY * scale, this.Grip03.pivotZ * scale);
        matrices.translate(this.Grip03.pitch * scale, this.Grip03.yaw * scale, this.Grip03.roll * scale);
        matrices.scale(0.99f, 1.0f, 1.0f);
        matrices.translate(-this.Grip03.pivotX * scale, -this.Grip03.pivotY * scale, -this.Grip03.pivotZ * scale);
        matrices.translate(-this.Grip03.pitch * scale, -this.Grip03.yaw * scale, -this.Grip03.roll * scale);
        this.Grip03.render(matrices, vertices, light, overlay);
        matrices.pop();
        this.Trigger02.render(matrices, vertices, light, overlay);
    }

}
